{% set name = "dropstackframe" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c264193d1941f247ecd719126a64b9c0fb06da83c4600fbb36ef061e4a135989

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry-core
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - dropstackframe
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jesnie/dropstackframe
  summary: 'A python library for dropping stack frames.'
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - westinhuang
